version: '3.8'

services:
  crawler:
    build: ./crawler
    volumes:
      - ./shared_data:/app/data
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./shared_data:/app/data
    depends_on:
      - crawler
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
